class Autogenerated {
  List<Data>? data;
  bool? success;
  int? status;

  Autogenerated({this.data, this.success, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    success = json['success'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = this.success;
    data['status'] = this.status;
    return data;
  }
}

class Data {
  String? id;
  String? title;
  String? description;
  int? datetime;
  String? type;
  bool? animated;
  int? width;
  int? height;
  int? size;
  int? views;
  String? link;
  String? deletehash;
  bool? favorite;
  bool? nsfw;
  String? section;
  String? accountUrl;
  int? accountId;
  bool? isAd;
  bool? inMostViral;
  bool? hasSound;
  List<String>? tags;
  int? adType;
  String? adUrl;
  bool? inGallery;
  String? mp4;
  String? gifv;
  int? mp4Size;
  String? linkFlairText;
  int? favoriteCount;
  int? commentCount;
  int? ups;
  int? downs;
  int? points;
  int? score;

  Data(
      {this.id,
      this.title,
      this.description,
      this.datetime,
      this.type,
      this.animated,
      this.width,
      this.height,
      this.size,
      this.views,
      this.link,
      this.deletehash,
      this.favorite,
      this.nsfw,
      this.section,
      this.accountUrl,
      this.accountId,
      this.isAd,
      this.inMostViral,
      this.hasSound,
      this.tags,
      this.adType,
      this.adUrl,
      this.inGallery,
      this.mp4,
      this.gifv,
      this.mp4Size,
      this.linkFlairText,
      this.favoriteCount,
      this.commentCount,
      this.ups,
      this.downs,
      this.points,
      this.score});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    description = json['description'];
    datetime = json['datetime'];
    type = json['type'];
    animated = json['animated'];
    width = json['width'];
    height = json['height'];
    size = json['size'];
    views = json['views'];
    link = json['link'];
    deletehash = json['deletehash'];
    favorite = json['favorite'];
    nsfw = json['nsfw'];
    section = json['section'];
    accountUrl = json['account_url'];
    accountId = json['account_id'];
    isAd = json['is_ad'];
    inMostViral = json['in_most_viral'];
    hasSound = json['has_sound'];
    tags = json['tags'].cast<String>();
    adType = json['ad_type'];
    adUrl = json['ad_url'];
    inGallery = json['in_gallery'];
    mp4 = json['mp4'];
    gifv = json['gifv'];
    mp4Size = json['mp4_size'];
    linkFlairText = json['link_flair_text'];
    favoriteCount = json['favorite_count'];
    commentCount = json['comment_count'];
    ups = json['ups'];
    downs = json['downs'];
    points = json['points'];
    score = json['score'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['description'] = this.description;
    data['datetime'] = this.datetime;
    data['type'] = this.type;
    data['animated'] = this.animated;
    data['width'] = this.width;
    data['height'] = this.height;
    data['size'] = this.size;
    data['views'] = this.views;
    data['link'] = this.link;
    data['deletehash'] = this.deletehash;
    data['favorite'] = this.favorite;
    data['nsfw'] = this.nsfw;
    data['section'] = this.section;
    data['account_url'] = this.accountUrl;
    data['account_id'] = this.accountId;
    data['is_ad'] = this.isAd;
    data['in_most_viral'] = this.inMostViral;
    data['has_sound'] = this.hasSound;
    data['tags'] = this.tags;
    data['ad_type'] = this.adType;
    data['ad_url'] = this.adUrl;
    data['in_gallery'] = this.inGallery;
    data['mp4'] = this.mp4;
    data['gifv'] = this.gifv;
    data['mp4_size'] = this.mp4Size;
    data['link_flair_text'] = this.linkFlairText;
    data['favorite_count'] = this.favoriteCount;
    data['comment_count'] = this.commentCount;
    data['ups'] = this.ups;
    data['downs'] = this.downs;
    data['points'] = this.points;
    data['score'] = this.score;
    return data;
  }
}
